### ISSUE TITLE
Is the handling of attribution appropriate throughout the exercise

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/rrtools-repro-research#6]
In the workshop we remix subsets of materials but twice within the exercise we define creator / author of materials we're creating.

In the `DESCRIPTION` and `README` of their research compendia, participants use their own names as creators but cite the work as a partial reproduction of Boettiger 2018 (following the convention of responses to papers). 

When rebuilding the paper though, we retain the original author's authorship details.

I felt this approach is most appropriate for a reproduction but could well be wrong. 

Am hoping licenses are also being handled appropriately (retained CC-BY 4.0 for docs and data (citing Boettiger as source) and MIT for code) but again not 100% sure it's sufficient. Thoughts welcome. 

@cboettig, @benmarwick any ideas? 🙏

**Comment by cboettig** [comment]
all sounds fine to me!

**Comment by annakrystalli** [comment]
Great! If you're happy, I'm happy!
